### PR TITLE
Pip requirements - closes #444

### LINKED ISSUE #444: pip requirements
Document all required python packages in a requirements.txt or any other way.

E.g.: for the Telegram plugin the *requests* package is required which isn't installed by default and i didn't find any documentation in the wiki - hmu if there is a documentation for it. ;)

### PR DESCRIPTION
**Pull request by LarsVomMars**
Added the requirements.txt files and some further instructions for easier install and usage of the plugins requiring separate pypi packages like the Telegram plugin.

### CODE REVIEW

**Comment by Schrolli91** [comment]
Please let me know, if you ready with this ...
And thanks for you help

**Comment by LarsVomMars** [comment]
If i haven't overlooked any extra packages every plugin which needs them should have a requirements.txt.

I left the MySQL Plugin out due to the installer which installs this plugin from source. So i didn't see the necessity of adding a requirements.txt for this - I can change this up tho ;)

**Review by Schrolli91 — APPROVED** [review]

**Comment by Schrolli91** [comment]
i think thats ok for now - but please make a note to the changelog as well

**Review by Schrolli91 — APPROVED** [review]

**Comment by Schrolli91** [comment]
Thank you

**Pull request merged**
